### ISSUE TITLE
Nunjucks Support

### ISSUE THREAD

**Issue by gangadharjannu** [artstorm/eleventy-plugin-seo#11]
## problem
I'm using the starter blog from https://github.com/11ty/eleventy-base-blog
Now I'm trying to use seo plugin for my blog. As mentioned in the document, I put `{% seo %}` in markdown files and it is working without any issues. 

However, the starter blog is inheriting templates so that we don't need to write all the HTML in every post.

Now my question is, how to use `{% seo %}` in nunjucks files? 

## current scenario
`{% seo %}` can only be defined at posts level. 

I tried to use the seo block in nunjucks but it is throwing error 

`TemplateWriterWriteError` was thrown
> (_includes/layouts/base.njk) [Line 11, Column 8]
  unknown block tag: seo

## Expected solution
seo block can be usable in markdown and nunjucks files

**Comment by artstorm** [comment]
@gangadharjannu Currently it's implemented for the Liquid engine. Expanding support so it also can work with Nunjucks engine is definitely worth considering.

**Comment by artstorm** [comment]
@gangadharjannu I just released v0.5.0 which has support for Nunjucks templating engine. So try the new version.

When using the plugin with Nunjucks the tag to use is 

```
{% seo "" %}
```

Ie, `""` needs to be added after `seo`.
