### ISSUE TITLE
Cannot override settings with front matter

### ISSUE THREAD

**Issue by tristanMatthias** [artstorm/eleventy-plugin-seo#21]
It works fine if I set it in the config file. However if I try to override in the template with front matter, it doesn't work. EG: `title`

```liquid
---
title: Not working
---

...
```

**Comment by artstorm** [comment]
@tristanMatthias 

The `title` in the config file is the title for the site, while the `title` in a page is for that page. So it is not supposed to override the title in the config. Instead the title in the config file gets appended to the page title. Ie, `page title | site title`.

What is the use case that you are trying to do?

**Comment by artstorm** [comment]
Closing as no further explanation of the issue was added.
